Fix test by creating link associations
The test was failing with
```
Failures:

  1) LinkApiResponsePresenter#present link is present returns combined details for the local authority and local interaction
     Failure/Error: "lgsl_code" => @link.service.lgsl_code,

     NoMethodError:
       undefined method `lgsl_code' for nil:NilClass
     # ./app/presenters/link_api_response_presenter.rb:31:in `link_details'
     # ./app/presenters/link_api_response_presenter.rb:9:in `present'
     # ./spec/presenters/link_api_response_presenter_spec.rb:27:in `block (4 levels) in <top (required)>'

```

This is because when building the `link`, its associations are ignored.
Creating (instead of building) the `link` solves this problem because it
also creates its associations that were previously not present.